lib/loofah/html5/scrub.rb
test/html5/test_sanitizer.rb

This is an extension of #59. It's very common when using data attributes to have a multi-word name like `data-user-email` or `data-shop-id`. However, the regex added in #59 wasn't general enough to allow these multi-word attributes so they are being scrubbed by the default scrubbers whereas single-word names like `data-user` are being passed over.
Sidenote: I double-checked the spec and separating words with dashes is definitely the correct way to be doing this
http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes
@flavorjones cc @rafaelfranca

Allow multi-word data attributes

---

.travis.yml
Gemfile

This PR changes the Travis setup to test on latest stable JRuby (9.1.5.0 and 1.7.26) and also on a recent Rubinius (rubinius 3.65 (2.3.1)).
- `rbx-19mode` never ran in the given configuration. It was not installed on the target build machine. Now the Travis config uses `rbx-3`. [Rubinius Travis Canary Build](https://travis-ci.org/rubinius/travis-canary) shows that `rbx-3` is there, so switched to that.
- To get a working installation of Rubinius available, I had to select another build server target (Ubuntu 14.04).
- `ruby-head` uses json gem 2.0 and rdoc 5.0.0.beta2 to make it through installation
- (I don't know Hoe, and how to add such a version-picking conditional in the Gemfile with that.)
- Travis' gce worker nodes needs an entropy-adding Debian package `haveged` to be able to …

Travis: build on JRuby 9.1.5.0, 1.7.26 and Rubinius 3

---

test/integration/test_helpers.rb

This PR avoids a warning in test output, by adding parentheses.
> /home/travis/build/flavorjones/loofah/test/integration/test_helpers.rb:40: warning: Ambiguous first argument; make sure.

Spec: avoid warning in test output

---

Gemfile
Rakefile

Hi,
I want to use `rr` latest version 1.2.0.
https://rubygems.org/gems/rr
I did not include updated `loofah.gemspec` in this PR. because you might update it by yourself.
I succeeded unit tests with updated `loofah.gemspec`.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle -v
Bundler version 1.14.3
$ bundle install --path vendor/bundle
$ bundle exec rake gemspec
$ rm -rf vendor/ .bundle/ Gemfile.lock
$ bundle install --path vendor/bundle
$ bundle list
Gems included by the bundle:
* bundler (1.14.3)
* crass (1.0.2)
* hoe (3.16.0)
* hoe-bundler (1.3.0)
* hoe-debugging (1.3.0)
* hoe-gemspec (1.0.0)
* hoe-git (1.6.0)
* json (2.0.3)
* mini_portile2 (2.1.0)
* minitest (2.12.1)
* nokogiri (1.7.0.1)
* rake (12.0.0)
* rdoc (5.0.0)
* rr (1.2.0)
$ bundle exec rake test …
```

Use rr-1.2 as a development dependency.

---

.travis.yml

Hello,
I want to add Ruby 2.4 to Travis CI.
`fast_finish` that I also added is to get the Travis result as faster without waiting the result of the `allow_failures` items.
See https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/ for detail.
Thanks.

Add Ruby 2.4 to Travis.

---

lib/loofah/html5/scrub.rb

This fixes following warning:
```
vendor/bundle/ruby/2.4.0/gems/loofah-2.1.0/lib/loofah/html5/scrub.rb:47: warning: assigned but unused variable - base64
```

Fix "warning: assigned but unused variable - base64"

---

lib/loofah/html5/whitelist.rb

Resolves https://github.com/flavorjones/loofah/issues/133

whitelist HTML5 <main> element

---

README.rdoc

The example:
```
unsafe_html = "ohai! <div>div is safe</div> <script>but script is not</script>"
doc = Loofah.fragment(unsafe_html).scrub!(:strip)
doc.to_s    # => "ohai! <div>div is safe</div> "
```
was not true to Loofah's output. Using the `:strip` scrubber would remove the `<script>` tag but leave its children, meaning that the actual value returned by `doc.to_s` would be:
```
"ohai! <div>div is safe</div> but script is not"
```
not:
```
"ohai! <div>div is safe</div> "
```
Using the `:prune` scrubber, on the other hand, removes the `<script>` tag along with its children, resulting in the latter value for `to_s`.

Fix inaccurate example in README

---

lib/loofah/html5/scrub.rb
lib/loofah/html5/whitelist.rb
test/html5/test_sanitizer.rb

A PR for #122 
I'm not 100% on the XSS concerns with enabling calc() by default.

Added ability to whitelist particular functions #122

---

lib/loofah/html5/whitelist.rb
test/html5/test_sanitizer.rb

In an effort to expedite the addition of list-style-type on PR #137 I've made this PR which removes the issues with version manipulation

Added list-style-type as a safe CSS property to whitelist

---

lib/loofah/html5/scrub.rb
test/html5/test_scrub.rb

```rb
Loofah::HTML5::Scrub.scrub_css("background: #0000A") # => ""
```
Should behave the same as
```rb
Loofah::HTML5::Scrub.scrub_css("background: #0000a") # => "background:#0000a;"
```

Correct the regexp for kewordish css property which hold hex values

---

CHANGELOG.md
lib/loofah/html5/whitelist.rb
test/html5/test_sanitizer.rb

Hello, first time contributing to loofah. I'm not sure if this should go in `ACCEPTABLE_CSS_PROPERTIES` or in `SHORTHAND_CSS_PROPERTIES` but of those two, only the former makes my test pass.

Allow CSS property `list-style`

---

lib/loofah/html5/whitelist.rb

They're used as values for the `border-width` property, which can be specified via the currently-allowed `border` shorthand property. (`medium` can also be used as a `border-width` value and is already allowed.)
See the [`<line-width>`](https://www.w3.org/TR/css-backgrounds-3/#typedef-line-width) type definition in the Backgrounds and Borders module of the CSS spec.

Allow the thin and thick CSS keywords

---

lib/loofah/html5/scrub.rb
test/html5/test_sanitizer.rb

css sanitizer allows "rem" sizes

---

loofah.gemspec

Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `mailing_list_uri`, `wiki_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/loofah and be available via the rubygems API after the next release.

Add project metadata to the gemspec

---

Rakefile
loofah.gemspec

#170 added metadata to the `loofah.gemspec`. These changes should be made to README. The `::` syntax is recommended by https://github.com/seattlerb/hoe/commit/e23f9803aefb2e283ba8211235d309ff94b55e9a.
This Pull Request is pending with https://github.com/seattlerb/hoe/pull/98/ to have metadata uri support for `wiki_uri` and `mailing_list_uri`.

Fix metadata of final gemspec

---

lib/loofah/html5/scrub.rb
test/html5/test_sanitizer.rb

Hi, loofah recently added `rem` (#177), thought we could support other length units too.
Found them on: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units.
Thanks.

[CSS Sanitizer] Allow more css length units

---

Manifest.txt
Rakefile

Hi! 
Take 2 of #179. Sorry, I wasn't aware this was generated by Hoe. 
After this Pull Request if you run `rake gemspec`:
```diff
-  s.extra_rdoc_files = ["CHANGELOG.md".freeze, "MIT-LICENSE.txt".freeze, "Manifest.txt".freeze, "README.md".freeze, "SECURITY.md".freeze, "CHANGELOG.md".freeze, "README.md".freeze, "SECURITY.md".freeze]
-  s.files = [".gemtest".freeze, "CHANGELOG.md".freeze, "Gemfile".freeze, "MIT-LICENSE.txt".freeze, "Manifest.txt".freeze, "README.md".freeze, "Rakefile".freeze, "SECURITY.md".freeze, "benchmark/benchmark.rb".freeze, "benchmark/fragment.html".freeze, "benchmark/helper.rb".freeze, "benchmark/www.slashdot.com.html".freeze, "lib/loofah.rb".freeze, "lib/loofah/elements.rb".freeze, "lib/loofah/helpers.rb".freeze, "lib/loofah/html/document.rb".freeze, …
```

Remove test files from final gem (take 2)

---

CHANGELOG.md
lib/loofah/html5/scrub.rb
test/assets/testdata_sanitizer_tests1.dat

fixed #191: scrub_css drops !important rule from shorthand css properties

---

CHANGELOG.md
lib/loofah/html5/scrub.rb
test/html5/test_scrub_css.rb
test/integration/test_ad_hoc.rb

This was broken in v2.9.0 by bf13d48
Fixes #202

fix: allow CSS properties to have quoted string values

---

test/assets/testdata_sanitizer_tests1.dat

This commit expands tests to cover an attack via unicode-encoded strings.
Let's work backwards. First, the failing test from `rails-html-sanitizer` (see https://github.com/rails/rails-html-sanitizer/issues/111):
```ruby
def test_should_sanitize_div_background_image_unicode_encoded
raw = %(background-image:\0075\0072\006C\0028'\006a\0061\0076\0061\0073\0063\0072\0069\0070\0074\003a\0061\006c\0065\0072\0074\0028.1027\0058.1053\0053\0027\0029'\0029)
assert_equal '', sanitize_css(raw)
end
```
This test started failing in Loofah v2.9.0. Why? Because it shouldn't have been getting filtered in the first place. When decoded, this string is simply `background-image:52C8'a161332904a1c5248.10278.1053379'9` which admittedly is garbage, but not _potentially harmful_ garbage.
:shrug: I'm fixing that …

test: actually test against a working unicode-encoded exploit

---

test/integration/test_ad_hoc.rb
test/integration/test_scrubbers.rb

Update tests to pass with this version of libxml2. See https://gitlab.gnome.org/GNOME/libxml2/-/commit/21ca882

test: libxml 2.9.11 handles namespaces in HTML docs differently

---

lib/loofah/html5/safelist.rb

Just run into the problem of overflow-x and y disappearing. 
It seems like the end-goal is to not to have to maintain a list like this, but at least in my use case overflow-y is used quite a bit. 
So it would be pretty great to have it as allowed property too!

Update safelist.rb to include overflow-x and y

---

CHANGELOG.md
lib/loofah/html5/safelist.rb
test/html5/test_sanitizer.rb

This PR introduces some changes:
- deprecate `HTML5::SafeList::VOID_ELEMENTS` which is not a canonical set of void elements
- remove unallowed elements from VOID_ELEMENTS
- remove elements that libxml2 doesn't actually treat as void from VOID_ELEMENTS
- allow `wbr` element
See #212 for background. See also https://developer.mozilla.org/en-US/docs/Glossary/Empty_element

allow HTML5 element `wbr`

---

CHANGELOG.md
lib/loofah/html5/scrub.rb
test/html5/test_sanitizer.rb

feat: support empty HTML5 data attributes

---

test/assets/testdata_sanitizer_tests1.dat

This adds onto #205. The original reported exploit in 2006 used CSS
hex encoding (e.g., "\0075" for "u"), which was ...
- mistakenly put into a double-quoted Ruby string in the Instiki test
suite in 2007,
- then copied into html5lib-ruby's test suite,
- then copied into html5lib-python's suite,
- then finally copied into the html5lib shared suite,
- which was imported into Loofah

test: use CSS hex-encoded strings to test sanitization

---

CHANGELOG.md
lib/loofah/instance_methods.rb
test/integration/test_html.rb

Previously any comment nodes that were top-level children of the fragment were serialized.
Closes #221

fix: comments should not be emitted by DocumentFragment#text

---

CHANGELOG.md
README.md
lib/loofah/elements.rb
lib/loofah/instance_methods.rb
lib/loofah/scrubbers.rb
test/integration/test_html.rb

which probably should have always been the desired behavior.
Closes #225

feat: Node#to_text replaces <br> with a newline

---

test/integration/test_ad_hoc.rb

see https://github.com/sparklemotion/nokogiri/issues/2461 for background

test: add coverage for entities

---

test/assets/testdata_sanitizer_tests1.dat

libxml2 v2.9.14 changes how ill-formed HTML4 is fixed up in recovery mode. See [release notes for Nokogiri v1.13.5](https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.5) and https://github.com/sparklemotion/nokogiri/issues/2525

test: ensure we pass with libxml 2.9.14

---

lib/loofah/html5/safelist.rb

Hey @flavorjones!
This PR simply adds [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) to the list of supported CSS properties.

Add aspect-ratio to the list of css properties

---

.github/workflows/ci.yml

to prevent the psych issue with older versions (ruby 2.5)

ci: ensure a min rubygems version

---

.github/workflows/ci.yml
loofah.gemspec
test/helper.rb
test/integration/test_scrubbers.rb
test/unit/test_helpers.rb

Let's just use MiniTest::Mock or MiniTest's stubbing.

dep: remove dependency on RR for mocking

---

.github/workflows/ci.yml

Fix the following warnings.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

Bump actions/checkout from 2 to 3

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
lib/loofah.rb
lib/loofah/concerns.rb
lib/loofah/helpers.rb
lib/loofah/html4/document.rb
lib/loofah/html4/document_fragment.rb
lib/loofah/html5/document.rb
lib/loofah/html5/document_fragment.rb
lib/loofah/html5/scrub.rb
lib/loofah/instance_methods.rb
lib/loofah/scrubber.rb
lib/loofah/scrubbers.rb
lib/loofah/xml/document_fragment.rb
test/assets/testdata_sanitizer_tests1.dat
test/helper.rb
test/html5/test_sanitizer.rb
test/integration/test_ad_hoc.rb
test/integration/test_html.rb
test/integration/test_scrubbers.rb
test/unit/test_api.rb
test/unit/test_encoding.rb
test/unit/test_helpers.rb
test/unit/test_scrubber.rb
test/unit/test_scrubbers.rb

The libgumbo parser used by Nokogiri::HTML5 is superior, standards-wise, to the libxml2 parser used by Nokogiri::HTML4 (the default).
This PR replaces #239. It has a much more flexible API that provides both html4 and html5 methods. It's up to the caller to choose which they want (note that the generic calls like `Loofah.fragment` still default to HTML4).
Note that testing in CI with older Rubies is sufficient to test older versions of Nokogiri, because Ruby 2.5 and 2.6 use Nokogiri 1.12 and 1.13, respectively, for precompiled binaries.

add html5 support, get jruby green

---

.rubocop.yml
Gemfile
Rakefile
test/helper.rb

**What problem is this PR intended to solve?**
Use `rubocop-packaging` to ensure Loofah continues to be easy to repackage.

dep(style): rubocop-packaging

---

test/integration/test_ad_hoc.rb
test/integration/test_scrubbers.rb

see note in https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.4

test: support libxml 2.10.4 behavior around namespaces

---

lib/loofah.rb
test/unit/test_api.rb

These classes require Nokogiri v1.14 in order to work properly.

don't define HTML5::Document and HTML5::DocumentFragment if HTML5 isn't supported

---

README.md
loofah.gemspec

Closes #266 
This PR updates the Nokogiri dependency to `>= 1.12.0`, and the Ruby dependency to `>= 2.5.0` (which matches the requirement of Nokogiri 1.12.x).

dep: require nokogiri >= 1.12.0

---

Gemfile

Pulls in fix from https://github.com/flavorjones/hoe-markdown/pull/1

dep: bump hoe-markdown for ruby 3.3 ci

---

lib/loofah/html5/scrub.rb
test/html5/test_scrub_css.rb

Keep whitespace if it is present, but do not insert any new whitespace that isn't there.
Fixes #271

fix: scrub_css is more consistent with whitespace

---

README.md
lib/loofah/scrubbers.rb
test/integration/test_scrubbers.rb

[fixes #272]
New scrubber `:targetblank` - adds a `target="_blank"` attribute to all links. If there is a target already set, replaces it with `target="_blank"`.
```
link_farmers_markup = "ohai! <a href='http://www.myswarmysite.com/'>I like your blog post</a>"
Loofah.html5_fragment(link_farmers_markup).scrub!(:targetblank)
=> "ohai! <a href='http://www.myswarmysite.com/' target="_blank">I like your blog post</a>"
```
(co-authored by @thdaraujo)

feat: adds `:targetblank` scrubber

---

README.md
lib/loofah/scrubbers.rb
test/integration/test_scrubbers.rb

Just like the existing nofollow and noopener add a noreferrer scrubber.

Add noreferrer scrubber

---

loofah.gemspec

I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to gemspec

---

.github/workflows/ci.yml

because jruby-head continues to have the jar-dependencies problem

ci: add ruby 3.4, drop jruby-head

---

lib/loofah/scrubbers.rb
test/integration/test_scrubbers.rb

Links like `<a href="#top">` should not receive a `target=_blank`.

Skip target attribute on links with anchors.

---

README.md
lib/loofah/scrubbers.rb
test/integration/test_scrubbers.rb

- Users would like to have functionality within loofah that provides the ability to replace double breakpoints into paragraph nodes
- Creating a new scrubber (`:double_breakpoint`) that replaces double breakpoints into paragraph nodes (thank you @flavorjones )
- Created a new integration test case. 
> [!IMPORTANT]  
> There is a failing test right now where the expectation and actual result match except for newline characters. In discussing with @flavorjones, this might be related to minitest and how it formats html
```sh
(ruby) doc.xpath("/html/body").inner_html
"<p>Some text here in a logical paragraph.</p><p>Some more text, apparently a second paragraph.</p><p>Et cetera...</p>"
(ruby) BREAKPOINT_RESULT
"<p>Some text here in a logical paragraph.</p><p>Some more text, apparently a second …
```

[RubyConf] Create scrubber for replacing double breakpoints into paragraph nodes

---

lib/loofah/html5/scrub.rb

In Ruby 3.5 most of the `cgi` gem will be removed. Only the various escape/unescape methods will be retained by default.
On older versions, `require "cgi/util"` is needed because the unescape* methods don't work otherwise.
https://bugs.ruby-lang.org/issues/21258

Only load what is required from `cgi`
